name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - to-gh-pages
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install clj runtime
      run: |
        cd "$HOME"
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
        chmod +x posix-install.sh
        sudo ./posix-install.sh

    - name: Build stylesheet
      uses: gha-utilities/sass-build@v0.5.1
      with:
          source: sass/css/main.scss
          destination: public/css/main.css

    - name: Build html
      run: clojure -X:generate-html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        allow_empty_commit: false
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
